// Regenerates src/actions.ts from server/openapi.json.
//
// The server spec is the contract (`pnpm --dir server gen:openapi` owns it); this
// script derives the compact catalog the MCP server ships so `tailchat_actions` and
// `tailchat_call` know every published action, its HTTP path, its parameters and the
// API-key scopes that permit it — without reading the server tree at runtime.
//
// Run `pnpm --dir apps/tailchat-mcp sync:actions` after regenerating the spec.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, '../../../server/openapi.json');
const outPath = resolve(here, '../src/actions.ts');

const spec = JSON.parse(readFileSync(specPath, 'utf8'));

/**
 * '/group/invite/createGroupInvite'  -> 'group.invite.createGroupInvite'
 * '/plugin:com.msgbyte.tasks/all'    -> 'plugin:com.msgbyte.tasks.all'
 * Core service names are dotted and the gateway path replaces every dot with a
 * slash; plugin service names keep their dots and only the action gets a slash.
 */
function pathToAction(path) {
  return path.replace(/^\//, '').split('/').join('.');
}

const actions = Object.entries(spec.paths)
  .map(([path, item]) => {
    const op = item.post;
    const schema = op?.requestBody?.content?.['application/json']?.schema ?? {};
    return {
      action: pathToAction(path),
      path,
      summary: op?.summary ?? '',
      scopes: op?.['x-tailchat-scopes'] ?? [],
      public: Array.isArray(op?.security) && op.security.length === 0,
      params: schema.properties ?? {},
      required: schema.required ?? [],
    };
  })
  .sort((a, b) => a.action.localeCompare(b.action));

const out = `// GENERATED by scripts/sync-actions.mjs from server/openapi.json — do not edit.
// Regenerate with: pnpm --dir apps/tailchat-mcp sync:actions

export interface ActionInfo {
  action: string;
  path: string;
  summary: string;
  scopes: string[];
  public: boolean;
  params: Record<string, unknown>;
  required: string[];
}

export const SPEC_VERSION = ${JSON.stringify(spec.info?.version ?? '0.0.0')};

export const ACTIONS: ActionInfo[] = ${JSON.stringify(actions, null, 2)};
`;

writeFileSync(outPath, out);
console.log(`wrote ${actions.length} actions to ${outPath}`);
