// GENERATED by scripts/sync-actions.mjs from server/openapi.json — do not edit.
// Regenerate with: pnpm --dir apps/tailchat-mcp sync:actions

export interface ActionInfo {
  action: string;
  path: string;
  summary: string;
  scopes: string[];
  public: boolean;
  params: Record<string, unknown>;
  required: string[];
}

export const SPEC_VERSION = '1.20.0';

export const ACTIONS: ActionInfo[] = [
  {
    action: 'admin.addGroupMember',
    path: '/admin/addGroupMember',
    summary: 'admin.addGroupMember',
    scopes: ['admin'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      userId: {
        type: 'string',
      },
    },
    required: ['groupId', 'userId'],
  },
  {
    action: 'admin.banUser',
    path: '/admin/banUser',
    summary: 'admin.banUser',
    scopes: ['admin'],
    public: false,
    params: {
      userId: {
        type: 'string',
      },
    },
    required: ['userId'],
  },
  {
    action: 'admin.findUser',
    path: '/admin/findUser',
    summary: 'admin.findUser',
    scopes: ['admin'],
    public: false,
    params: {
      email: {
        type: 'string',
      },
      username: {
        type: 'string',
      },
    },
    required: [],
  },
  {
    action: 'admin.notifyUsers',
    path: '/admin/notifyUsers',
    summary: 'admin.notifyUsers',
    scopes: ['admin'],
    public: false,
    params: {
      userIds: {
        type: 'array',
        items: {
          type: 'string',
        },
        minItems: 1,
      },
      title: {
        type: 'string',
      },
      content: {
        type: 'string',
      },
    },
    required: ['userIds', 'title', 'content'],
  },
  {
    action: 'admin.unbanUser',
    path: '/admin/unbanUser',
    summary: 'admin.unbanUser',
    scopes: ['admin'],
    public: false,
    params: {
      userId: {
        type: 'string',
      },
    },
    required: ['userId'],
  },
  {
    action: 'chat.ack.all',
    path: '/chat/ack/all',
    summary: 'chat.ack.all',
    scopes: ['message:read'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'chat.ack.list',
    path: '/chat/ack/list',
    summary: 'chat.ack.list',
    scopes: ['message:read'],
    public: false,
    params: {
      converseIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['converseIds'],
  },
  {
    action: 'chat.ack.update',
    path: '/chat/ack/update',
    summary: 'chat.ack.update',
    scopes: ['message:write'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
      lastMessageId: {
        type: 'string',
      },
    },
    required: ['converseId', 'lastMessageId'],
  },
  {
    action: 'chat.converse.appendDMConverseMembers',
    path: '/chat/converse/appendDMConverseMembers',
    summary: 'chat.converse.appendDMConverseMembers',
    scopes: [],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
      memberIds: {
        type: 'array',
      },
    },
    required: ['converseId', 'memberIds'],
  },
  {
    action: 'chat.converse.createDMConverse',
    path: '/chat/converse/createDMConverse',
    summary: 'chat.converse.createDMConverse',
    scopes: ['message:write'],
    public: false,
    params: {
      memberIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['memberIds'],
  },
  {
    action: 'chat.converse.findAndJoinRoom',
    path: '/chat/converse/findAndJoinRoom',
    summary: 'chat.converse.findAndJoinRoom',
    scopes: ['message:read'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'chat.converse.findConverseInfo',
    path: '/chat/converse/findConverseInfo',
    summary: 'chat.converse.findConverseInfo',
    scopes: ['message:read'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
    },
    required: ['converseId'],
  },
  {
    action: 'chat.inbox.ack',
    path: '/chat/inbox/ack',
    summary: 'chat.inbox.ack',
    scopes: ['message:write'],
    public: false,
    params: {
      inboxItemIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['inboxItemIds'],
  },
  {
    action: 'chat.inbox.all',
    path: '/chat/inbox/all',
    summary: 'chat.inbox.all',
    scopes: ['message:read'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'chat.inbox.clear',
    path: '/chat/inbox/clear',
    summary: 'chat.inbox.clear',
    scopes: ['message:write'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'chat.message.addReaction',
    path: '/chat/message/addReaction',
    summary: 'chat.message.addReaction',
    scopes: ['message:write'],
    public: false,
    params: {
      messageId: {
        type: 'string',
      },
      emoji: {
        type: 'string',
      },
    },
    required: ['messageId', 'emoji'],
  },
  {
    action: 'chat.message.deleteMessage',
    path: '/chat/message/deleteMessage',
    summary: 'chat.message.deleteMessage',
    scopes: ['message:write'],
    public: false,
    params: {
      messageId: {
        type: 'string',
      },
    },
    required: ['messageId'],
  },
  {
    action: 'chat.message.fetchConverseLastMessages',
    path: '/chat/message/fetchConverseLastMessages',
    summary: 'chat.message.fetchConverseLastMessages',
    scopes: [],
    public: false,
    params: {
      converseIds: {
        type: 'array',
      },
    },
    required: ['converseIds'],
  },
  {
    action: 'chat.message.fetchConverseMessage',
    path: '/chat/message/fetchConverseMessage',
    summary: 'chat.message.fetchConverseMessage',
    scopes: ['message:read'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
      startId: {
        type: 'string',
      },
    },
    required: ['converseId'],
  },
  {
    action: 'chat.message.fetchNearbyMessage',
    path: '/chat/message/fetchNearbyMessage',
    summary: 'chat.message.fetchNearbyMessage',
    scopes: ['message:read'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      converseId: {
        type: 'string',
      },
      messageId: {
        type: 'string',
      },
      num: {
        type: 'number',
      },
    },
    required: ['converseId', 'messageId'],
  },
  {
    action: 'chat.message.getMessage',
    path: '/chat/message/getMessage',
    summary: 'chat.message.getMessage',
    scopes: ['message:read'],
    public: false,
    params: {
      messageId: {
        type: 'string',
      },
    },
    required: ['messageId'],
  },
  {
    action: 'chat.message.getSlowModeStatus',
    path: '/chat/message/getSlowModeStatus',
    summary: 'chat.message.getSlowModeStatus',
    scopes: ['message:read'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
      groupId: {
        type: 'string',
      },
    },
    required: ['converseId', 'groupId'],
  },
  {
    action: 'chat.message.recallMessage',
    path: '/chat/message/recallMessage',
    summary: 'chat.message.recallMessage',
    scopes: ['message:write'],
    public: false,
    params: {
      messageId: {
        type: 'string',
      },
    },
    required: ['messageId'],
  },
  {
    action: 'chat.message.removeReaction',
    path: '/chat/message/removeReaction',
    summary: 'chat.message.removeReaction',
    scopes: ['message:write'],
    public: false,
    params: {
      messageId: {
        type: 'string',
      },
      emoji: {
        type: 'string',
      },
    },
    required: ['messageId', 'emoji'],
  },
  {
    action: 'chat.message.searchMessage',
    path: '/chat/message/searchMessage',
    summary: 'chat.message.searchMessage',
    scopes: ['message:read'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      converseId: {
        type: 'string',
      },
      text: {
        type: 'string',
      },
    },
    required: ['converseId', 'text'],
  },
  {
    action: 'chat.message.sendMessage',
    path: '/chat/message/sendMessage',
    summary: 'chat.message.sendMessage',
    scopes: ['message:write'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
      groupId: {
        type: 'string',
      },
      content: {
        type: 'string',
      },
      plain: {
        type: 'string',
      },
      meta: {},
    },
    required: ['converseId', 'content'],
  },
  {
    action: 'config.client',
    path: '/config/client',
    summary: 'config.client',
    scopes: [],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'debug.hello',
    path: '/debug/hello',
    summary: 'debug.hello',
    scopes: [],
    public: true,
    params: {
      name: {
        type: 'string',
      },
    },
    required: [],
  },
  {
    action: 'debug.sleep',
    path: '/debug/sleep',
    summary: 'debug.sleep',
    scopes: [],
    public: false,
    params: {
      second: {
        type: 'number',
      },
    },
    required: ['second'],
  },
  {
    action: 'file.get',
    path: '/file/get',
    summary: 'file.get',
    scopes: ['file'],
    public: false,
    params: {
      objectName: {
        type: 'string',
      },
    },
    required: ['objectName'],
  },
  {
    action: 'file.save',
    path: '/file/save',
    summary: 'file.save',
    scopes: ['file'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'file.stat',
    path: '/file/stat',
    summary: 'file.stat',
    scopes: ['file'],
    public: false,
    params: {
      objectName: {
        type: 'string',
      },
    },
    required: ['objectName'],
  },
  {
    action: 'friend.buildFriendRelation',
    path: '/friend/buildFriendRelation',
    summary: 'friend.buildFriendRelation',
    scopes: ['user:write'],
    public: false,
    params: {
      user1: {
        type: 'string',
      },
      user2: {
        type: 'string',
      },
    },
    required: ['user1', 'user2'],
  },
  {
    action: 'friend.checkIsFriend',
    path: '/friend/checkIsFriend',
    summary: 'friend.checkIsFriend',
    scopes: ['user:read', 'user:write'],
    public: false,
    params: {
      targetId: {
        type: 'string',
      },
    },
    required: ['targetId'],
  },
  {
    action: 'friend.getAllFriends',
    path: '/friend/getAllFriends',
    summary: 'friend.getAllFriends',
    scopes: ['user:read', 'user:write'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'friend.removeFriend',
    path: '/friend/removeFriend',
    summary: 'friend.removeFriend',
    scopes: ['user:write'],
    public: false,
    params: {
      friendUserId: {
        type: 'string',
      },
    },
    required: ['friendUserId'],
  },
  {
    action: 'friend.request.accept',
    path: '/friend/request/accept',
    summary: 'friend.request.accept',
    scopes: ['user:write'],
    public: false,
    params: {
      requestId: {
        type: 'string',
      },
    },
    required: ['requestId'],
  },
  {
    action: 'friend.request.add',
    path: '/friend/request/add',
    summary: 'friend.request.add',
    scopes: ['user:write'],
    public: false,
    params: {
      to: {
        type: 'string',
      },
      message: {
        type: 'string',
      },
    },
    required: ['to'],
  },
  {
    action: 'friend.request.allRelated',
    path: '/friend/request/allRelated',
    summary: 'friend.request.allRelated',
    scopes: ['user:write'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'friend.request.cancel',
    path: '/friend/request/cancel',
    summary: 'friend.request.cancel',
    scopes: ['user:write'],
    public: false,
    params: {
      requestId: {
        type: 'string',
      },
    },
    required: ['requestId'],
  },
  {
    action: 'friend.request.deny',
    path: '/friend/request/deny',
    summary: 'friend.request.deny',
    scopes: ['user:write'],
    public: false,
    params: {
      requestId: {
        type: 'string',
      },
    },
    required: ['requestId'],
  },
  {
    action: 'friend.setFriendNickname',
    path: '/friend/setFriendNickname',
    summary: 'friend.setFriendNickname',
    scopes: ['user:write'],
    public: false,
    params: {
      targetId: {
        type: 'string',
      },
      nickname: {
        type: 'string',
      },
    },
    required: ['targetId', 'nickname'],
  },
  {
    action: 'group.addGroupMember',
    path: '/group/addGroupMember',
    summary: 'group.addGroupMember',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      userId: {
        type: 'string',
      },
    },
    required: ['groupId', 'userId'],
  },
  {
    action: 'group.appendGroupMemberRoles',
    path: '/group/appendGroupMemberRoles',
    summary: 'group.appendGroupMemberRoles',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      memberIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
      roles: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['groupId', 'memberIds', 'roles'],
  },
  {
    action: 'group.createGroup',
    path: '/group/createGroup',
    summary: 'group.createGroup',
    scopes: ['group:manage'],
    public: false,
    params: {
      name: {
        type: 'string',
      },
      panels: {
        type: 'array',
      },
    },
    required: ['name', 'panels'],
  },
  {
    action: 'group.createGroupPanel',
    path: '/group/createGroupPanel',
    summary: 'group.createGroupPanel',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
      type: {
        type: 'number',
      },
      parentId: {
        type: 'string',
      },
      provider: {
        type: 'string',
      },
      pluginPanelName: {
        type: 'string',
      },
      meta: {
        type: 'object',
      },
    },
    required: ['groupId', 'name', 'type'],
  },
  {
    action: 'group.createGroupRole',
    path: '/group/createGroupRole',
    summary: 'group.createGroupRole',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      roleName: {
        type: 'string',
      },
      permissions: {
        type: 'array',
        items: {
          type: 'string',
        },
        default: [],
      },
    },
    required: ['groupId', 'roleName'],
  },
  {
    action: 'group.deleteGroupMember',
    path: '/group/deleteGroupMember',
    summary: 'group.deleteGroupMember',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      memberId: {
        type: 'string',
      },
    },
    required: ['groupId', 'memberId'],
  },
  {
    action: 'group.deleteGroupPanel',
    path: '/group/deleteGroupPanel',
    summary: 'group.deleteGroupPanel',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
    },
    required: ['groupId', 'panelId'],
  },
  {
    action: 'group.deleteGroupRole',
    path: '/group/deleteGroupRole',
    summary: 'group.deleteGroupRole',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      roleId: {
        type: 'string',
      },
    },
    required: ['groupId', 'roleId'],
  },
  {
    action: 'group.extra.getGroupData',
    path: '/group/extra/getGroupData',
    summary: 'group.extra.getGroupData',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
    },
    required: ['groupId', 'name'],
  },
  {
    action: 'group.extra.getPanelData',
    path: '/group/extra/getPanelData',
    summary: 'group.extra.getPanelData',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
    },
    required: ['groupId', 'panelId', 'name'],
  },
  {
    action: 'group.extra.saveGroupData',
    path: '/group/extra/saveGroupData',
    summary: 'group.extra.saveGroupData',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
      data: {
        type: 'string',
      },
    },
    required: ['groupId', 'name', 'data'],
  },
  {
    action: 'group.extra.savePanelData',
    path: '/group/extra/savePanelData',
    summary: 'group.extra.savePanelData',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
      data: {
        type: 'string',
      },
    },
    required: ['groupId', 'panelId', 'name', 'data'],
  },
  {
    action: 'group.getGroupBasicInfo',
    path: '/group/getGroupBasicInfo',
    summary: 'group.getGroupBasicInfo',
    scopes: ['group:read', 'group:manage'],
    public: true,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.getGroupLobbyConverseId',
    path: '/group/getGroupLobbyConverseId',
    summary: 'group.getGroupLobbyConverseId',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.getJoinedGroupAndPanelIds',
    path: '/group/getJoinedGroupAndPanelIds',
    summary: 'group.getJoinedGroupAndPanelIds',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'group.getPermissions',
    path: '/group/getPermissions',
    summary: 'group.getPermissions',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.getUserGroups',
    path: '/group/getUserGroups',
    summary: 'group.getUserGroups',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'group.invite.applyInvite',
    path: '/group/invite/applyInvite',
    summary: 'group.invite.applyInvite',
    scopes: ['group:manage'],
    public: false,
    params: {
      code: {
        type: 'string',
      },
    },
    required: ['code'],
  },
  {
    action: 'group.invite.createGroupInvite',
    path: '/group/invite/createGroupInvite',
    summary: 'group.invite.createGroupInvite',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      inviteType: {
        enum: ['normal', 'permanent'],
      },
    },
    required: ['groupId', 'inviteType'],
  },
  {
    action: 'group.invite.deleteInvite',
    path: '/group/invite/deleteInvite',
    summary: 'group.invite.deleteInvite',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      inviteId: {
        type: 'string',
      },
    },
    required: ['groupId', 'inviteId'],
  },
  {
    action: 'group.invite.editGroupInvite',
    path: '/group/invite/editGroupInvite',
    summary: 'group.invite.editGroupInvite',
    scopes: ['group:manage'],
    public: false,
    params: {
      code: {
        type: 'string',
      },
      groupId: {
        type: 'string',
      },
      expiredAt: {
        type: 'number',
      },
      usageLimit: {
        type: 'number',
      },
    },
    required: ['code', 'groupId'],
  },
  {
    action: 'group.invite.findInviteByCode',
    path: '/group/invite/findInviteByCode',
    summary: 'group.invite.findInviteByCode',
    scopes: ['group:read', 'group:manage'],
    public: true,
    params: {
      code: {
        type: 'string',
      },
    },
    required: ['code'],
  },
  {
    action: 'group.invite.getAllGroupInviteCode',
    path: '/group/invite/getAllGroupInviteCode',
    summary: 'group.invite.getAllGroupInviteCode',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.isGroupOwner',
    path: '/group/isGroupOwner',
    summary: 'group.isGroupOwner',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.isMember',
    path: '/group/isMember',
    summary: 'group.isMember',
    scopes: ['group:read', 'group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.modifyGroupPanel',
    path: '/group/modifyGroupPanel',
    summary: 'group.modifyGroupPanel',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
      type: {
        type: 'number',
      },
      provider: {
        type: 'string',
      },
      pluginPanelName: {
        type: 'string',
      },
      meta: {
        type: 'object',
      },
      permissionMap: {
        type: 'object',
      },
      fallbackPermissions: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['groupId', 'panelId', 'name', 'type'],
  },
  {
    action: 'group.muteGroupMember',
    path: '/group/muteGroupMember',
    summary: 'group.muteGroupMember',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      memberId: {
        type: 'string',
      },
      muteMs: {
        type: 'number',
      },
    },
    required: ['groupId', 'memberId', 'muteMs'],
  },
  {
    action: 'group.quitGroup',
    path: '/group/quitGroup',
    summary: 'group.quitGroup',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'group.removeGroupMemberRoles',
    path: '/group/removeGroupMemberRoles',
    summary: 'group.removeGroupMemberRoles',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      memberIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
      roles: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['groupId', 'memberIds', 'roles'],
  },
  {
    action: 'group.updateGroupConfig',
    path: '/group/updateGroupConfig',
    summary: 'group.updateGroupConfig',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      configName: {
        type: 'string',
      },
      configValue: {},
    },
    required: ['groupId', 'configName', 'configValue'],
  },
  {
    action: 'group.updateGroupField',
    path: '/group/updateGroupField',
    summary: 'group.updateGroupField',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      fieldName: {
        type: 'string',
      },
      fieldValue: {},
    },
    required: ['groupId', 'fieldName', 'fieldValue'],
  },
  {
    action: 'group.updateGroupRoleName',
    path: '/group/updateGroupRoleName',
    summary: 'group.updateGroupRoleName',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      roleId: {
        type: 'string',
      },
      roleName: {
        type: 'string',
      },
    },
    required: ['groupId', 'roleId', 'roleName'],
  },
  {
    action: 'group.updateGroupRolePermission',
    path: '/group/updateGroupRolePermission',
    summary: 'group.updateGroupRolePermission',
    scopes: ['group:manage'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      roleId: {
        type: 'string',
      },
      permissions: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['groupId', 'roleId', 'permissions'],
  },
  {
    action: 'openapi.app.all',
    path: '/openapi/app/all',
    summary: 'openapi.app.all',
    scopes: [],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'openapi.app.authToken',
    path: '/openapi/app/authToken',
    summary: 'openapi.app.authToken',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      token: {
        type: 'string',
      },
      capability: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['appId', 'token'],
  },
  {
    action: 'openapi.app.create',
    path: '/openapi/app/create',
    summary: 'openapi.app.create',
    scopes: [],
    public: false,
    params: {
      appName: {
        type: 'string',
      },
      appDesc: {
        type: 'string',
      },
      appIcon: {
        type: 'string',
      },
    },
    required: ['appName', 'appDesc', 'appIcon'],
  },
  {
    action: 'openapi.app.delete',
    path: '/openapi/app/delete',
    summary: 'openapi.app.delete',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
    },
    required: ['appId'],
  },
  {
    action: 'openapi.app.get',
    path: '/openapi/app/get',
    summary: 'openapi.app.get',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
    },
    required: ['appId'],
  },
  {
    action: 'openapi.app.setAppBotInfo',
    path: '/openapi/app/setAppBotInfo',
    summary: 'openapi.app.setAppBotInfo',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      fieldName: {
        type: 'string',
      },
      fieldValue: {},
    },
    required: ['appId', 'fieldName', 'fieldValue'],
  },
  {
    action: 'openapi.app.setAppCapability',
    path: '/openapi/app/setAppCapability',
    summary: 'openapi.app.setAppCapability',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      capability: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['appId', 'capability'],
  },
  {
    action: 'openapi.app.setAppInfo',
    path: '/openapi/app/setAppInfo',
    summary: 'openapi.app.setAppInfo',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      fieldName: {
        type: 'string',
      },
      fieldValue: {
        type: 'string',
      },
    },
    required: ['appId', 'fieldName', 'fieldValue'],
  },
  {
    action: 'openapi.app.setAppOAuthInfo',
    path: '/openapi/app/setAppOAuthInfo',
    summary: 'openapi.app.setAppOAuthInfo',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      fieldName: {
        type: 'string',
      },
      fieldValue: {},
    },
    required: ['appId', 'fieldName', 'fieldValue'],
  },
  {
    action: 'openapi.bot.login',
    path: '/openapi/bot/login',
    summary: 'openapi.bot.login',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      token: {
        type: 'string',
      },
    },
    required: ['appId', 'token'],
  },
  {
    action: 'openapi.integration.addBotUser',
    path: '/openapi/integration/addBotUser',
    summary: 'openapi.integration.addBotUser',
    scopes: [],
    public: false,
    params: {
      appId: {
        type: 'string',
      },
      groupId: {
        type: 'string',
      },
    },
    required: ['appId', 'groupId'],
  },
  {
    action: 'plugin:com.msgbyte.agora.available',
    path: '/plugin:com.msgbyte.agora/available',
    summary: 'plugin:com.msgbyte.agora.available',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.discover.all',
    path: '/plugin:com.msgbyte.discover/all',
    summary: 'plugin:com.msgbyte.discover.all',
    scopes: ['plugins'],
    public: false,
    params: {
      page: {
        type: 'number',
        default: 1,
      },
      size: {
        type: 'number',
        default: 20,
      },
    },
    required: ['page', 'size'],
  },
  {
    action: 'plugin:com.msgbyte.discover.join',
    path: '/plugin:com.msgbyte.discover/join',
    summary: 'plugin:com.msgbyte.discover.join',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'plugin:com.msgbyte.getui.available',
    path: '/plugin:com.msgbyte.getui/available',
    summary: 'plugin:com.msgbyte.getui.available',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.github.subscribe.add',
    path: '/plugin:com.msgbyte.github.subscribe/add',
    summary: 'plugin:com.msgbyte.github.subscribe.add',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      textPanelId: {
        type: 'string',
      },
      repoName: {
        type: 'string',
      },
    },
    required: ['groupId', 'textPanelId', 'repoName'],
  },
  {
    action: 'plugin:com.msgbyte.github.subscribe.delete',
    path: '/plugin:com.msgbyte.github.subscribe/delete',
    summary: 'plugin:com.msgbyte.github.subscribe.delete',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      subscribeId: {
        type: 'string',
      },
    },
    required: ['groupId', 'subscribeId'],
  },
  {
    action: 'plugin:com.msgbyte.github.subscribe.list',
    path: '/plugin:com.msgbyte.github.subscribe/list',
    summary: 'plugin:com.msgbyte.github.subscribe.list',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
    },
    required: ['groupId'],
  },
  {
    action: 'plugin:com.msgbyte.github.subscribe.webhook.callback',
    path: '/plugin:com.msgbyte.github.subscribe/webhook.callback',
    summary: 'plugin:com.msgbyte.github.subscribe.webhook.callback',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.iam.availableStrategies',
    path: '/plugin:com.msgbyte.iam/availableStrategies',
    summary: 'plugin:com.msgbyte.iam.availableStrategies',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.linkmeta.fetch',
    path: '/plugin:com.msgbyte.linkmeta/fetch',
    summary: 'plugin:com.msgbyte.linkmeta.fetch',
    scopes: ['plugins'],
    public: false,
    params: {
      url: {
        type: 'string',
      },
    },
    required: ['url'],
  },
  {
    action: 'plugin:com.msgbyte.livekit.available',
    path: '/plugin:com.msgbyte.livekit/available',
    summary: 'plugin:com.msgbyte.livekit.available',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.prettyinvite.badge',
    path: '/plugin:com.msgbyte.prettyinvite/badge',
    summary: 'plugin:com.msgbyte.prettyinvite.badge',
    scopes: ['plugins'],
    public: false,
    params: {
      inviteCode: {
        type: 'string',
      },
    },
    required: ['inviteCode'],
  },
  {
    action: 'plugin:com.msgbyte.simplenotify.addGroupSubscribe',
    path: '/plugin:com.msgbyte.simplenotify/addGroupSubscribe',
    summary: 'plugin:com.msgbyte.simplenotify.addGroupSubscribe',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      textPanelId: {
        type: 'string',
      },
    },
    required: ['groupId', 'textPanelId'],
  },
  {
    action: 'plugin:com.msgbyte.simplenotify.addUserSubscribe',
    path: '/plugin:com.msgbyte.simplenotify/addUserSubscribe',
    summary: 'plugin:com.msgbyte.simplenotify.addUserSubscribe',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.simplenotify.delete',
    path: '/plugin:com.msgbyte.simplenotify/delete',
    summary: 'plugin:com.msgbyte.simplenotify.delete',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      subscribeId: {
        type: 'string',
      },
    },
    required: ['groupId', 'subscribeId'],
  },
  {
    action: 'plugin:com.msgbyte.simplenotify.list',
    path: '/plugin:com.msgbyte.simplenotify/list',
    summary: 'plugin:com.msgbyte.simplenotify.list',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      type: {
        enum: ['user', 'group'],
      },
    },
    required: ['groupId', 'type'],
  },
  {
    action: 'plugin:com.msgbyte.simplenotify.webhook.callback',
    path: '/plugin:com.msgbyte.simplenotify/webhook.callback',
    summary: 'plugin:com.msgbyte.simplenotify.webhook.callback',
    scopes: ['plugins'],
    public: false,
    params: {
      subscribeId: {
        type: 'string',
      },
      text: {
        type: 'string',
      },
    },
    required: ['subscribeId', 'text'],
  },
  {
    action: 'plugin:com.msgbyte.tasks.add',
    path: '/plugin:com.msgbyte.tasks/add',
    summary: 'plugin:com.msgbyte.tasks.add',
    scopes: ['plugins'],
    public: false,
    params: {
      title: {
        type: 'string',
      },
      assignee: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
      description: {
        type: 'string',
      },
      expiredAt: {
        type: 'string',
      },
    },
    required: ['title'],
  },
  {
    action: 'plugin:com.msgbyte.tasks.all',
    path: '/plugin:com.msgbyte.tasks/all',
    summary: 'plugin:com.msgbyte.tasks.all',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin:com.msgbyte.tasks.done',
    path: '/plugin:com.msgbyte.tasks/done',
    summary: 'plugin:com.msgbyte.tasks.done',
    scopes: ['plugins'],
    public: false,
    params: {
      taskId: {
        type: 'string',
      },
    },
    required: ['taskId'],
  },
  {
    action: 'plugin:com.msgbyte.tasks.undone',
    path: '/plugin:com.msgbyte.tasks/undone',
    summary: 'plugin:com.msgbyte.tasks.undone',
    scopes: ['plugins'],
    public: false,
    params: {
      taskId: {
        type: 'string',
      },
    },
    required: ['taskId'],
  },
  {
    action: 'plugin:com.msgbyte.tasks.update',
    path: '/plugin:com.msgbyte.tasks/update',
    summary: 'plugin:com.msgbyte.tasks.update',
    scopes: ['plugins'],
    public: false,
    params: {
      taskId: {
        type: 'string',
      },
      title: {
        type: 'string',
      },
      assignee: {
        type: 'string',
      },
      description: {
        type: 'string',
      },
      expiredAt: {
        type: 'string',
      },
    },
    required: ['taskId'],
  },
  {
    action: 'plugin:com.msgbyte.topic.create',
    path: '/plugin:com.msgbyte.topic/create',
    summary: 'plugin:com.msgbyte.topic.create',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      content: {
        type: 'string',
      },
      meta: {
        type: 'object',
      },
    },
    required: ['groupId', 'panelId', 'content'],
  },
  {
    action: 'plugin:com.msgbyte.topic.createComment',
    path: '/plugin:com.msgbyte.topic/createComment',
    summary: 'plugin:com.msgbyte.topic.createComment',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      topicId: {
        type: 'string',
      },
      content: {
        type: 'string',
      },
      replyCommentId: {
        type: 'string',
      },
    },
    required: ['groupId', 'panelId', 'topicId', 'content'],
  },
  {
    action: 'plugin:com.msgbyte.topic.delete',
    path: '/plugin:com.msgbyte.topic/delete',
    summary: 'plugin:com.msgbyte.topic.delete',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      topicId: {
        type: 'string',
      },
    },
    required: ['groupId', 'panelId', 'topicId'],
  },
  {
    action: 'plugin:com.msgbyte.topic.list',
    path: '/plugin:com.msgbyte.topic/list',
    summary: 'plugin:com.msgbyte.topic.list',
    scopes: ['plugins'],
    public: false,
    params: {
      groupId: {
        type: 'string',
      },
      panelId: {
        type: 'string',
      },
      page: {
        type: 'number',
      },
      size: {
        type: 'number',
      },
    },
    required: ['groupId', 'panelId'],
  },
  {
    action: 'plugin:com.msgbyte.wxpusher.available',
    path: '/plugin:com.msgbyte.wxpusher/available',
    summary: 'plugin:com.msgbyte.wxpusher.available',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'plugin.registry.list',
    path: '/plugin/registry/list',
    summary: 'plugin.registry.list',
    scopes: ['plugins'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'user.apikey.create',
    path: '/user/apikey/create',
    summary: 'user.apikey.create',
    scopes: [],
    public: false,
    params: {
      name: {
        type: 'string',
        minLength: 1,
        maxLength: 64,
      },
      scopes: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
      expiresInDays: {
        type: 'integer',
        exclusiveMinimum: 0,
      },
    },
    required: ['name', 'scopes'],
  },
  {
    action: 'user.apikey.list',
    path: '/user/apikey/list',
    summary: 'user.apikey.list',
    scopes: [],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'user.apikey.revoke',
    path: '/user/apikey/revoke',
    summary: 'user.apikey.revoke',
    scopes: [],
    public: false,
    params: {
      keyId: {
        type: 'string',
      },
    },
    required: ['keyId'],
  },
  {
    action: 'user.apikey.scopes',
    path: '/user/apikey/scopes',
    summary: 'user.apikey.scopes',
    scopes: [],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'user.checkTokenValid',
    path: '/user/checkTokenValid',
    summary: 'user.checkTokenValid',
    scopes: [],
    public: true,
    params: {
      token: {
        type: 'string',
      },
    },
    required: ['token'],
  },
  {
    action: 'user.claimTemporaryUser',
    path: '/user/claimTemporaryUser',
    summary: 'user.claimTemporaryUser',
    scopes: [],
    public: false,
    params: {
      userId: {
        type: 'string',
      },
      username: {
        type: 'string',
        maxLength: 40,
      },
      email: {
        type: 'string',
        maxLength: 40,
        format: 'email',
      },
      password: {
        type: 'string',
        maxLength: 40,
      },
      emailOTP: {
        type: 'string',
      },
    },
    required: ['userId', 'email', 'password'],
  },
  {
    action: 'user.createTemporaryUser',
    path: '/user/createTemporaryUser',
    summary: 'user.createTemporaryUser',
    scopes: [],
    public: true,
    params: {
      nickname: {
        type: 'string',
      },
    },
    required: ['nickname'],
  },
  {
    action: 'user.dmlist.addConverse',
    path: '/user/dmlist/addConverse',
    summary: 'user.dmlist.addConverse',
    scopes: ['user:write'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
    },
    required: ['converseId'],
  },
  {
    action: 'user.dmlist.getAllConverse',
    path: '/user/dmlist/getAllConverse',
    summary: 'user.dmlist.getAllConverse',
    scopes: ['user:read', 'user:write'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'user.dmlist.removeConverse',
    path: '/user/dmlist/removeConverse',
    summary: 'user.dmlist.removeConverse',
    scopes: ['user:write'],
    public: false,
    params: {
      converseId: {
        type: 'string',
      },
    },
    required: ['converseId'],
  },
  {
    action: 'user.ensureOpenapiBot',
    path: '/user/ensureOpenapiBot',
    summary: 'user.ensureOpenapiBot',
    scopes: [],
    public: false,
    params: {
      botId: {
        type: 'string',
      },
      nickname: {
        type: 'string',
      },
      avatar: {
        type: 'string',
      },
    },
    required: ['botId', 'nickname'],
  },
  {
    action: 'user.ensurePluginBot',
    path: '/user/ensurePluginBot',
    summary: 'user.ensurePluginBot',
    scopes: [],
    public: false,
    params: {
      botId: {
        type: 'string',
      },
      nickname: {
        type: 'string',
      },
      avatar: {
        type: 'string',
      },
    },
    required: ['botId', 'nickname'],
  },
  {
    action: 'user.findOpenapiBotId',
    path: '/user/findOpenapiBotId',
    summary: 'user.findOpenapiBotId',
    scopes: [],
    public: false,
    params: {
      email: {
        type: 'string',
      },
    },
    required: ['email'],
  },
  {
    action: 'user.forgetPassword',
    path: '/user/forgetPassword',
    summary: 'user.forgetPassword',
    scopes: [],
    public: false,
    params: {
      email: {
        type: 'string',
        format: 'email',
      },
    },
    required: ['email'],
  },
  {
    action: 'user.getUserInfo',
    path: '/user/getUserInfo',
    summary: 'user.getUserInfo',
    scopes: ['user:read'],
    public: true,
    params: {
      userId: {
        type: 'string',
      },
    },
    required: ['userId'],
  },
  {
    action: 'user.getUserInfoList',
    path: '/user/getUserInfoList',
    summary: 'user.getUserInfoList',
    scopes: ['user:read'],
    public: true,
    params: {
      userIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['userIds'],
  },
  {
    action: 'user.getUserSettings',
    path: '/user/getUserSettings',
    summary: 'user.getUserSettings',
    scopes: ['user:read'],
    public: false,
    params: {},
    required: [],
  },
  {
    action: 'user.login',
    path: '/user/login',
    summary: 'user.login',
    scopes: [],
    public: true,
    params: {
      username: {
        type: 'string',
      },
      email: {
        type: 'string',
        format: 'email',
      },
      password: {
        type: 'string',
      },
    },
    required: ['password'],
  },
  {
    action: 'user.modifyPassword',
    path: '/user/modifyPassword',
    summary: 'user.modifyPassword',
    scopes: [],
    public: false,
    params: {
      oldPassword: {
        type: 'string',
      },
      newPassword: {
        type: 'string',
      },
    },
    required: ['oldPassword', 'newPassword'],
  },
  {
    action: 'user.register',
    path: '/user/register',
    summary: 'user.register',
    scopes: [],
    public: true,
    params: {
      username: {
        type: 'string',
        maxLength: 40,
      },
      email: {
        type: 'string',
        maxLength: 40,
        format: 'email',
      },
      nickname: {
        type: 'string',
        maxLength: 40,
      },
      password: {
        type: 'string',
        maxLength: 40,
      },
      emailOTP: {
        type: 'string',
      },
      avatar: {
        type: 'string',
      },
    },
    required: ['password'],
  },
  {
    action: 'user.resetPassword',
    path: '/user/resetPassword',
    summary: 'user.resetPassword',
    scopes: [],
    public: false,
    params: {
      email: {
        type: 'string',
        format: 'email',
      },
      password: {
        type: 'string',
      },
      otp: {
        type: 'string',
      },
    },
    required: ['email', 'password', 'otp'],
  },
  {
    action: 'user.resolveToken',
    path: '/user/resolveToken',
    summary: 'user.resolveToken',
    scopes: [],
    public: true,
    params: {
      token: {
        type: 'string',
      },
    },
    required: ['token'],
  },
  {
    action: 'user.searchUserWithUniqueName',
    path: '/user/searchUserWithUniqueName',
    summary: 'user.searchUserWithUniqueName',
    scopes: ['user:read'],
    public: false,
    params: {
      uniqueName: {
        type: 'string',
      },
    },
    required: ['uniqueName'],
  },
  {
    action: 'user.setUserSettings',
    path: '/user/setUserSettings',
    summary: 'user.setUserSettings',
    scopes: ['user:write'],
    public: false,
    params: {
      settings: {
        type: 'object',
      },
    },
    required: ['settings'],
  },
  {
    action: 'user.updateUserExtra',
    path: '/user/updateUserExtra',
    summary: 'user.updateUserExtra',
    scopes: ['user:write'],
    public: false,
    params: {
      fieldName: {
        type: 'string',
      },
      fieldValue: {},
    },
    required: ['fieldName', 'fieldValue'],
  },
  {
    action: 'user.updateUserField',
    path: '/user/updateUserField',
    summary: 'user.updateUserField',
    scopes: ['user:write'],
    public: false,
    params: {
      fieldName: {
        type: 'string',
      },
      fieldValue: {},
    },
    required: ['fieldName', 'fieldValue'],
  },
  {
    action: 'user.verifyEmail',
    path: '/user/verifyEmail',
    summary: 'user.verifyEmail',
    scopes: [],
    public: false,
    params: {
      email: {
        type: 'string',
        format: 'email',
      },
    },
    required: ['email'],
  },
  {
    action: 'user.verifyEmailWithOTP',
    path: '/user/verifyEmailWithOTP',
    summary: 'user.verifyEmailWithOTP',
    scopes: [],
    public: false,
    params: {
      emailOTP: {
        type: 'string',
      },
    },
    required: ['emailOTP'],
  },
  {
    action: 'user.whoami',
    path: '/user/whoami',
    summary: 'user.whoami',
    scopes: ['user:read'],
    public: false,
    params: {},
    required: [],
  },
];
