import {
  getCachedServerPlugins,
  parseUrlStr,
  PluginManifest,
} from 'tailchat-shared';
import { initMiniStar } from 'mini-star';
import _once from 'lodash/once';
import _uniqBy from 'lodash/uniqBy';
import { builtinPlugins } from './builtin';
import { showPluginLoadError } from './showPluginLoadError';

/**
 * Plugin manager.
 *
 * What loads is the SERVER's decision. There is no client-side install: the
 * list is the built-in set plus whatever the server reports it has installed,
 * and nothing in the browser can add to it.
 *
 * Upstream kept installs in `localStorage.$TailchatInstalledPlugins`, which
 * made "install" a per-browser act with no server sync — a panel one person
 * added simply failed to render for everyone else — and exposed
 * `window.tailchat.installPlugin`, which loaded arbitrary remote code into the
 * app under the signed-in user's session. Both are gone.
 */
class PluginManager {
  /**
   * Load every plugin this server offers.
   *
   * A server that cannot be reached still boots the built-in set: those ship
   * inside the same image as the client, so they are always present, and
   * failing closed here would leave the app with no panels at all.
   */
  initPlugins = _once(async () => {
    const plugins = _uniqBy(
      [...builtinPlugins, ...(await this.getServerPlugins())],
      'name'
    ).map(({ name, url }) => ({
      name,
      url: parseUrlStr(url),
    }));

    const loadErrorPlugins = new Set<string>();
    await initMiniStar({
      plugins,
      onPluginLoadError: (err) => {
        console.error('Plugin load error:', err);
        loadErrorPlugins.add(err.pluginName);
      },
    });

    if (loadErrorPlugins.size > 0) {
      showPluginLoadError(Array.from(loadErrorPlugins));
    }
  });

  /**
   * Plugins the server reports as installed.
   *
   * `registry-be.json` is generated by `server/scripts/installPlugin.js` at
   * image build time, so it is not a catalogue of what could be installed —
   * it is what this server actually has on disk.
   */
  private async getServerPlugins(): Promise<PluginManifest[]> {
    try {
      const plugins = await getCachedServerPlugins();

      return Array.isArray(plugins) ? plugins : [];
    } catch (err) {
      console.error('Failed to fetch server plugin list:', err);

      return [];
    }
  }

  /**
   * The plugins currently loaded, for display only.
   */
  async getInstalledPlugins(): Promise<PluginManifest[]> {
    return _uniqBy(
      [...builtinPlugins, ...(await this.getServerPlugins())],
      'name'
    );
  }
}

export const pluginManager = new PluginManager();
